package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-24T01:33:28.743-06:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ACCotizacion", 
                  wsdlLocation = "http://web.abaseguros.com/AutoConnect/ACCotizacion.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ACCotizacion extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ACCotizacion");
    public final static QName Default = new QName("http://tempuri.org/", "Default");
    static {
        URL url = null;
        try {
            url = new URL("http://web.abaseguros.com/AutoConnect/ACCotizacion.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ACCotizacion.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://web.abaseguros.com/AutoConnect/ACCotizacion.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ACCotizacion(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ACCotizacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ACCotizacion() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ACCotizacion(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ACCotizacion(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ACCotizacion(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IACCotizacion
     */
    @WebEndpoint(name = "Default")
    public IACCotizacion getDefault() {
        return super.getPort(Default, IACCotizacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IACCotizacion
     */
    @WebEndpoint(name = "Default")
    public IACCotizacion getDefault(WebServiceFeature... features) {
        return super.getPort(Default, IACCotizacion.class, features);
    }

}
