
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-24T01:33:28.618-06:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "Error", targetNamespace = "http://schemas.datacontract.org/2004/07/Abaseguros.AutoConnect")
public class IACCotizacionCotizaWsAutoErrorFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.abaseguros.Error error;

    public IACCotizacionCotizaWsAutoErrorFaultFaultMessage() {
        super();
    }
    
    public IACCotizacionCotizaWsAutoErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public IACCotizacionCotizaWsAutoErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IACCotizacionCotizaWsAutoErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.abaseguros.Error error) {
        super(message);
        this.error = error;
    }

    public IACCotizacionCotizaWsAutoErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.abaseguros.Error error, Throwable cause) {
        super(message, cause);
        this.error = error;
    }

    public org.datacontract.schemas._2004._07.abaseguros.Error getFaultInfo() {
        return this.error;
    }
}
