package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-24T01:33:28.711-06:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IACCotizacion")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.abaseguros.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IACCotizacion {

    @WebMethod(operationName = "CotizaAuto_AS", action = "http://tempuri.org/IACCotizacion/CotizaAuto_AS")
    @Action(input = "http://tempuri.org/IACCotizacion/CotizaAuto_AS", output = "http://tempuri.org/IACCotizacion/CotizaAuto_ASResponse", fault = {@FaultAction(className = IACCotizacionCotizaAutoASErrorFaultFaultMessage.class, value = "http://tempuri.org/IACCotizacion/CotizaAuto_ASErrorFault")})
    @WebResult(name = "Salida", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Salida cotizaAutoAS(
        @WebParam(partName = "parameters", name = "Entrada", targetNamespace = "http://tempuri.org/")
        Entrada parameters,
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://tempuri.org/", header = true)
        org.datacontract.schemas._2004._07.abaseguros.Token token
    ) throws IACCotizacionCotizaAutoASErrorFaultFaultMessage;

    @WebMethod(operationName = "CotizaAuto", action = "http://tempuri.org/IACCotizacion/CotizaAuto")
    @Action(input = "http://tempuri.org/IACCotizacion/CotizaAuto", output = "http://tempuri.org/IACCotizacion/CotizaAutoResponse", fault = {@FaultAction(className = IACCotizacionCotizaAutoErrorFaultFaultMessage.class, value = "http://tempuri.org/IACCotizacion/CotizaAutoErrorFault")})
    @WebResult(name = "Salida", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Salida cotizaAuto(
        @WebParam(partName = "parameters", name = "Entrada", targetNamespace = "http://tempuri.org/")
        Entrada parameters,
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://tempuri.org/", header = true)
        org.datacontract.schemas._2004._07.abaseguros.Token token
    ) throws IACCotizacionCotizaAutoErrorFaultFaultMessage;

    @WebMethod(operationName = "CotizaWsAuto", action = "http://tempuri.org/IACCotizacion/CotizaWsAuto")
    @Action(input = "http://tempuri.org/IACCotizacion/CotizaWsAuto", output = "http://tempuri.org/IACCotizacion/CotizaWsAutoResponse", fault = {@FaultAction(className = IACCotizacionCotizaWsAutoErrorFaultFaultMessage.class, value = "http://tempuri.org/IACCotizacion/CotizaWsAutoErrorFault")})
    @WebResult(name = "Salida", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Salida cotizaWsAuto(
        @WebParam(partName = "parameters", name = "Entrada", targetNamespace = "http://tempuri.org/")
        Entrada parameters,
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://tempuri.org/", header = true)
        org.datacontract.schemas._2004._07.abaseguros.Token token
    ) throws IACCotizacionCotizaWsAutoErrorFaultFaultMessage;
}
